const Map<String, String> ar = {
  'Smart Park': 'سمارت بارك',
  'Create your account': 'أنشئ حسابك',
  'Join Smart Park and reserve your parking spot faster, easier, and smarter.':
      'انضم إلى سمارت بارك واحجز موقفك بشكل أسرع وأسهل وأذكى.',
  'Sign up': 'إنشاء حساب',
  'Fill in your details to start exploring garages and booking your next parking spot.':
      'أدخل بياناتك لبدء استكشاف الكراجات وحجز موقفك القادم.',
  'Full Name': 'الاسم الكامل',
  'Enter your full name': 'أدخل اسمك الكامل',
  'Name is required': 'الاسم مطلوب',
  'Name must be at least 3 characters': 'الاسم يجب أن يكون 3 أحرف على الأقل',
  'Email': 'البريد الإلكتروني',
  'Enter your email': 'أدخل بريدك الإلكتروني',
  'example@email.com': 'example@email.com',
  'Email is required': 'البريد الإلكتروني مطلوب',
  'Enter a valid email': 'أدخل بريدًا إلكترونيًا صحيحًا',
  'Car Owner': 'صاحب سيارة',
  'Garage Owner': 'صاحب كراج',
  'Car Type': 'نوع السيارة',
  'Choose your car type': 'اختر نوع سيارتك',
  'Car type is required': 'نوع السيارة مطلوب',
  'Sedan': 'سيدان',
  'SUV': 'دفع رباعي',
  'Hatchback': 'هاتشباك',
  'Coupe': 'كوبيه',
  'Convertible': 'مكشوفة',
  'Pickup': 'بيك أب',
  'Van': 'فان',
  'Wagon': 'واجن',
  'Jeep': 'جيب',
  'Motorcycle': 'دراجة نارية',
  'Password': 'كلمة المرور',
  'Enter your password': 'أدخل كلمة المرور',
  'Password is required': 'كلمة المرور مطلوبة',
  'Password must be at least 6 characters':
      'كلمة المرور يجب أن تكون 6 أحرف على الأقل',
  'Confirm Password': 'تأكيد كلمة المرور',
  'Re-enter your password': 'أعد إدخال كلمة المرور',
  'Confirm password is required': 'تأكيد كلمة المرور مطلوب',
  'Passwords do not match': 'كلمتا المرور غير متطابقتين',
  'Create Account': 'إنشاء الحساب',
  'After signup, you can explore garages by city, view prices and availability, and reserve your parking spot in seconds.':
      'بعد إنشاء الحساب، يمكنك استكشاف الكراجات حسب المدينة، ومعرفة الأسعار والتوفر، وحجز موقفك خلال ثوانٍ.',
  'Already have an account? ': 'لديك حساب بالفعل؟ ',
  'Login': 'تسجيل الدخول',
  'Welcome back': 'مرحبًا بعودتك',
  'Reserve your parking spot before you arrive.': 'احجز موقفك قبل الوصول.',
  'Log in to find nearby garages and book a spot in seconds.':
      'سجل الدخول للعثور على الكراجات القريبة وحجز موقف خلال ثوانٍ.',
  'Login failed. Please check your credentials.':
      'فشل تسجيل الدخول. يرجى التحقق من بياناتك.',
  'Registration failed. Please try again.': 'فشل إنشاء الحساب. حاول مرة أخرى.',
  'Smart Park helps drivers reduce time spent searching for parking by showing availability and allowing quick reservations.':
      'يساعد سمارت بارك السائقين على تقليل الوقت الضائع في البحث عن المواقف من خلال عرض التوفر وإتاحة الحجز السريع.',
  'Don’t have an account? ': 'ليس لديك حساب؟ ',
  'Sign Up': 'إنشاء حساب',
  '© @year Smart Park': '© @year سمارت بارك',
  '© @year Smart Park • Parking made simple': '© @year سمارت بارك • مواقف أبسط',
  'Welcome to Smart Park': 'مرحباً بك في سمارت بارك',
  'Find garages and reserve your parking spot easily.':
      'ابحث عن الكراجات واحجز موقفك بسهولة.',
  'Find Garages': 'البحث عن الكراجات',
  'My Reservations': 'حجوزاتي',
  'Cities': 'المدن',
  'Favorites': 'المفضلة',
  'Choose Your Role': 'اختر نوع الحساب',
  'Select how you want to use Smart Park.': 'اختر كيف تريد استخدام سمارت بارك.',
  'Find garages, check availability, and reserve your parking spot.':
      'ابحث عن الكراجات، تحقق من التوفر، واحجز موقفك.',
  'Manage your garage, parking spaces, and reservations.':
      'قم بإدارة الكراج الخاص بك، المساحات، والحجوزات.',
  'Already have an account? Login': 'لديك حساب بالفعل؟ تسجيل الدخول',
  'Complete your garage profile to make it visible for car owners.':
      'أكمل معلومات الكراج ليظهر لأصحاب السيارات.',
  'Enter garage name': 'أدخل اسم الكراج',
  'Enter city': 'أدخل المدينة',
  'Enter address': 'أدخل العنوان',
  'Write a short description': 'اكتب وصفًا قصيرًا',
  'Garage Owner Home': 'الرئيسية لصاحب الكراج',
  'You have not added your garage information yet.':
      'أنت لم تقم بإضافة معلومات الكراج بعد.',
  'Please add your garage information to make it visible for car owners.':
      'يرجى إضافة معلومات الكراج ليصبح ظاهرًا لأصحاب السيارات.',
  'Your garage information has been added successfully.':
      'تمت إضافة معلومات الكراج بنجاح.',
  'Manage your garage and reservations from here.':
      'قم بإدارة الكراج والحجوزات من هنا.',
  'Available Spots': 'المواقف المتاحة',
  'Quick Actions': 'إجراءات سريعة',
  'Edit Garage': 'تعديل الكراج',
  'Reservations': 'الحجوزات',
  'Update Availability': 'تحديث التوفر',
  'Statistics': 'الإحصائيات',
  'Garage Name': 'اسم الكراج',
  'Garage name is required': 'اسم الكراج مطلوب',
  'City': 'المدينة',
  'City is required': 'المدينة مطلوبة',
  'Address': 'العنوان',
  'Address is required': 'العنوان مطلوب',
  'Price Per Hour': 'السعر لكل ساعة',
  'Price is required': 'السعر مطلوب',
  'Capacity': 'السعة',
  'Capacity is required': 'السعة مطلوبة',
  'Open Time': 'وقت الفتح',
  'Close Time': 'وقت الإغلاق',
  'Description': 'الوصف',
  'Save Garage Information': 'حفظ معلومات الكراج',
  'Failed to add garage information': 'فشل في إضافة معلومات الكراج',
  'Garage added successfully': 'تمت إضافة الكراج بنجاح',
  "Update your garage details": "قم بتحديث معلومات الكراج",
  "View booking requests": "عرض طلبات الحجز",
  "Manage available spaces": "إدارة المواقف المتاحة",
  "Check garage performance": "الاطلاع على أداء الكراج",
  "Open": "فتح",

  "Access Denied": "تم رفض الوصول",
  "Only garage owners can access this page":
      "فقط مالك الكراج يمكنه الوصول إلى هذه الصفحة",
  "No Garage Found": "لا يوجد كراج",
  "Garage information not found": "لم يتم العثور على معلومات الكراج",
  "Garage Information": "معلومات الكراج",
  "Garage Availability": "توفر الكراج",
  "Update your current available parking spots and garage status":
      "قم بتحديث عدد المواقف المتاحة الحالية وحالة الكراج",
  "Garage Capacity": "سعة الكراج",
  "Available spots is required": "عدد المواقف المتاحة مطلوب",
  "Enter a valid number": "أدخل رقمًا صحيحًا",
  "Available spots cannot be negative":
      "لا يمكن أن يكون عدد المواقف المتاحة سالبًا",
  "Available spots cannot be greater than capacity":
      "لا يمكن أن يكون عدد المواقف المتاحة أكبر من السعة",
  "Garage Active": "الكراج فعال",
  "Garage availability updated successfully": "تم تحديث توفر الكراج بنجاح",
  "Failed to update garage availability": "فشل تحديث توفر الكراج",

  "Save Changes": "حفظ التعديلات",
  "Saving...": "جاري الحفظ...",
  "Success": "نجاح",
  "Garage information updated successfully": "تم تحديث معلومات الكراج بنجاح",
  "Error": "خطأ",
  "Failed to update garage information": "فشل تحديث معلومات الكراج",
  "Something went wrong": "حدث خطأ ما",
  "Settings": "الإعدادات",
  "User": "المستخدم",
  "My Information": "معلوماتي",
  "View your account details": "عرض تفاصيل حسابك",
  "Change Password": "تغيير كلمة المرور",
  "Update your account password": "تحديث كلمة مرور حسابك",
  "Language": "اللغة",
  "Change app language": "تغيير لغة التطبيق",
  "Terms & Conditions": "الشروط والأحكام",
  "Read app terms and conditions": "قراءة الشروط والأحكام الخاصة بالتطبيق",
  "Contact Support": "التواصل مع الدعم",
  "Get help from support team": "احصل على المساعدة من فريق الدعم",
  "Logout": "تسجيل الخروج",
  "Sign out from your account": "تسجيل الخروج من حسابك",
  "Name": "الاسم",
  "Phone": "رقم الهاتف",
  "Role": "الدور",
  "Current Password": "كلمة المرور الحالية",
  "New Password": "كلمة المرور الجديدة",
  "Save": "حفظ",
  "Please fill all password fields": "يرجى تعبئة جميع حقول كلمة المرور",
  "New password and confirm password do not match":
      "كلمة المرور الجديدة وتأكيد كلمة المرور غير متطابقين",
  "Password changed successfully": "تم تغيير كلمة المرور بنجاح",
  "Failed to change password": "فشل تغيير كلمة المرور",
  "Language changed successfully": "تم تغيير اللغة بنجاح",
  "Failed to load user information": "فشل تحميل معلومات المستخدم",
  "Here you can put your application terms and conditions text.":
      "يمكنك وضع نص الشروط والأحكام الخاصة بالتطبيق هنا.",
  "Introduction": "المقدمة",
  "User Accounts": "حساب المستخدم",
  "Service Description": "وصف الخدمة",
  "Payments": "الدفع",
  "Garage Owner Responsibilities": "مسؤوليات صاحب الكراج",
  "Prohibited Use": "الاستخدام الممنوع",
  "Account Suspension": "إيقاف الحساب",
  "Limitation of Liability": "تحديد المسؤولية",
  "Privacy": "الخصوصية",
  "Changes to Terms": "تعديل الشروط",
  "Contact": "التواصل",
  "Smart Park Terms": "شروط Smart Park",
  "Please read these terms carefully before using the application.":
      "يرجى قراءة هذه الشروط بعناية قبل استخدام التطبيق.",
  "Welcome to Smart Park. By using this application, you agree to comply with and be bound by these terms and conditions.":
      "مرحبًا بك في Smart Park. باستخدام هذا التطبيق، فإنك توافق على الالتزام بهذه الشروط والأحكام.",
  "You must provide accurate information. You are responsible for your account and all activities under it.":
      "يجب إدخال معلومات صحيحة. أنت مسؤول عن حسابك وكل الأنشطة المرتبطة به.",
  "Smart Park allows users to search, reserve parking, and manage garages.":
      "يتيح التطبيق للمستخدمين البحث عن المواقف وحجزها وإدارة الكراجات.",
  "Reservations depend on availability. Users must respect booking time.":
      "تعتمد الحجوزات على التوفر ويجب الالتزام بوقت الحجز.",
  "Prices are set by garage owners. Payments must be completed properly.":
      "يتم تحديد الأسعار من قبل أصحاب الكراجات ويجب إتمام الدفع بشكل صحيح.",
  "Garage owners must provide accurate data and update availability.":
      "يجب على أصحاب الكراجات إدخال بيانات صحيحة وتحديث التوفر.",
  "Users must not misuse the app or perform illegal activities.":
      "يُمنع إساءة استخدام التطبيق أو القيام بأنشطة غير قانونية.",
  "We may suspend accounts that violate the terms.":
      "يحق لنا إيقاف الحسابات المخالفة.",
  "Smart Park is not responsible for damages or losses in parking locations.":
      "التطبيق غير مسؤول عن أي أضرار أو خسائر في المواقف.",
  "Your data is handled securely and respectfully.":
      "يتم التعامل مع بياناتك بأمان واحترام.",
  "We may update terms anytime. Continued use means acceptance.":
      "قد نقوم بتحديث الشروط في أي وقت، واستمرارك يعني الموافقة.",
  "Contact support for any questions.": "لأي استفسار يرجى التواصل مع الدعم.",
  "Contact Us": "تواصل معنا",
  "Subject": "الموضوع",
  "Message": "الرسالة",
  "Send Message": "إرسال الرسالة",
  "Sending...": "جاري الإرسال...",
  "Message sent successfully": "تم إرسال الرسالة بنجاح",
  "Failed to send message": "فشل إرسال الرسالة",
  "We are here to help": "نحن هنا لمساعدتك",
  "Send us your question, issue, or suggestion and we will get back to you.":
      "أرسل لنا سؤالك أو مشكلتك أو اقتراحك وسنقوم بالرد عليك.",
  "Our support team reviews messages as soon as possible.":
      "يقوم فريق الدعم بمراجعة الرسائل في أقرب وقت ممكن.",
  "Required": "مطلوب",
  "Welcome": "مرحباً",
  "Reserve your parking spot quickly and manage your activities easily.":
      "احجز موقفك بسرعة وأدر أنشطتك بسهولة.",
  "Make Reservation": "إنشاء حجز",
  "Find a garage and reserve a parking spot":
      "ابحث عن كراج واحجز موقفاً للسيارة",
  "Previous Reservations": "الحجوزات السابقة",
  "View your old and current reservations": "عرض حجوزاتك الحالية والسابقة",
  "Favorite Garages": "الكراجات المفضلة",
  "See your saved favorite garages": "عرض الكراجات التي أضفتها للمفضلة",
  "Manage your account and preferences": "إدارة حسابك وتفضيلاتك",
  "Send a message to support": "أرسل رسالة إلى الدعم",
  "make_reservation": "إجراء حجز",
  "fill_reservation_information": "أدخل معلومات الحجز",
  "reservation_date": "تاريخ الحجز",
  "start_time": "وقت البدء",
  "end_time": "وقت الانتهاء",
  "number_of_spots": "عدد المواقف",
  "confirm_reservation": "تأكيد الحجز",
  "my_reservations": "حجوزاتي",
  "upcoming": "القادمة",
  "previous": "السابقة",
  "no_upcoming_reservations": "لا يوجد حجوزات قادمة",
  "no_previous_reservations": "لا يوجد حجوزات سابقة",
  "cancel_reservation": "إلغاء الحجز",
  "reservation_created_successfully": "تم إنشاء الحجز بنجاح",
  "reservation_cancelled_successfully": "تم إلغاء الحجز بنجاح",
  "success": "نجاح",
  "error": "خطأ",
  "something_went_wrong": "حدث خطأ ما",
  "status": "الحالة",
  "total_cost": "التكلفة الإجمالية",
  "cancel_reason": "سبب الإلغاء",
  "owner_note": "ملاحظة صاحب الكراج",
  "enter_cancel_reason_optional": "أدخل سبب الإلغاء (اختياري)",
  "close": "إغلاق",
  "confirm": "تأكيد",
  "pending": "قيد الانتظار",
  "accepted": "مقبول",
  "rejected": "مرفوض",
  "cancelled": "ملغي",
  "completed": "مكتمل",
  "find_garages": "البحث عن الكراجات",
  "no_garages_found": "لا يوجد كراجات",
  "garage": "كراج",
  "available_spots": "المواقف المتاحة",
  "price_per_hour": "السعر لكل ساعة",
  "search_garages": "ابحث عن كراجات",
  "all_countries": "كل الدول",
  "country": "الدولة",
  "not_available": "غير متاح",
  "all_cities": "كل المدن",
  "no_reservations": "لا يوجد حجوزات",
  "accept": "قبول",
  "reject": "رفض",
  "cancel": "إلغاء",
  "optional_note": "ملاحظة اختيارية",
  "spots": "عدد المواقف",
  "favorite_garages": "الكراجات المفضلة",
  "no_favorites_found": "لا توجد كراجات مفضلة",
  "city": "المدينة",
  "Total": "الإجمالي",
  "total_revenue": "الأرباح",
  "reservations_breakdown": "توزيع الحجوزات",
  "Mobile":"الهاتف" ,
  "Mobile is required" : "يرجى أدخال رقم الهاتف",

  "details": "التفاصيل",
  "no_garage_data": "معلومات الكراج غير متوفرة",
  "ratings": "التقييمات",
  "no_ratings_yet": "لا توجد تقييمات بعد",
  "refresh": "تحديث",

  "rate_garage": "قيّم الكراج",
  "leave_a_comment_optional": "اترك تعليقًا (اختياري)",
  "submit": "إرسال",
  "submitting": "جاري الإرسال...",
  "rating_submitted_successfully": "تم إرسال التقييم بنجاح",

  "notifications": "الإشعارات",
  "no_notifications": "لا توجد إشعارات بعد",
  "mark_all_read": "تحديد الكل كمقروء",

  "report_garage": "تبليغ عن الكراج",
  "report_garage_subtitle":
      "أخبرنا بالمشكلة الموجودة في هذا الكراج وسيقوم فريقنا بمراجعتها.",
  "submit_report": "إرسال التبليغ",
  "report_submitted_successfully": "تم إرسال التبليغ بنجاح",
  "cancel_window_closed": "انتهت فترة الإلغاء (أقل من ساعتين متبقية)",

  "check_in": "تسجيل الوصول",
  "checked_in_successfully": "تم تسجيل الوصول بنجاح",

  "total": "الإجمالي",
  "revenue": "الأرباح",
  "statistics": "الإحصائيات",


  "mark_as_completed": "تحديد كمكتمل",
  "complete_reservation_confirm":
      "هل أنت متأكد من تحديد هذا الحجز كمكتمل؟ سيتم إشعار صاحب السيارة ويمكنه بعد ذلك تقييم تجربته.",
  "no_pending_or_accepted": "لا توجد حجوزات معلقة أو مقبولة",
  "reservation_completed_successfully": "تم تحديد الحجز كمكتمل بنجاح",
  "completed_reservations": "مكتملة",

  // تسجيل الخروج
  "check_out": "تسجيل الخروج",
  "checked_out_successfully": "تم تسجيل الخروج بنجاح",

  // الدفع
  "payment": "الدفع",
  "order_summary": "ملخص الطلب",
  "amount_due": "المبلغ المستحق",
  "card_number": "رقم البطاقة",
  "card_holder": "اسم حامل البطاقة",
  "card_expiry": "تاريخ الانتهاء (MM/YY)",
  "card_cvv": "رمز الأمان CVV",
  "pay": "ادفع",
  "pay_and_reserve": "ادفع واحجز",
  "processing": "جاري المعالجة...",
  "payment_successful": "تم الدفع بنجاح",
  "payment_failed": "فشلت عملية الدفع. استخدم بطاقة التجربة.",
  "use_demo_card": "استخدام بطاقة التجربة",
  "demo_card_banner":
      "وضع تجريبي: فقط البطاقة 4242 4242 4242 4242 وتاريخ 12/30 ورمز 123 سيُقبل.",

  // اختيار طريقة الدفع
  "pay_with_card": "بطاقة",
  "pay_with_cash": "نقداً",
  "cash_on_arrival": "ادفع نقداً عند الوصول",
  "cash_on_arrival_subtitle":
      "احجز الآن وادفع لصاحب الكراج نقداً عند وصولك.",
  "reserve_cash_payment": "احجز وادفع عند الوصول",
  "cash_payment_reserved": "تم تأكيد الحجز. ادفع عند الوصول.",

  // صور الكراج
  "garage_photos": "صور الكراج",
  "manage_photos_subtitle": "رفع وإدارة صور الكراج",
  "no_photos_yet": "لا توجد صور بعد",
  "tap_to_add_photos": "اضغط الزر أعلاه لإضافة صور",
  "add_photos": "إضافة صور",
  "photos_count": "الصور",
  "delete_photo": "حذف الصورة",
  "delete_photo_confirm": "هل أنت متأكد من حذف هذه الصورة؟",
  "delete": "حذف",
  "photos_uploaded_successfully": "تم رفع الصور بنجاح",
  "photo_deleted": "تم حذف الصورة",

  // خدمات الكراج
  "garage_services": "خدمات الكراج",
  "manage_services_subtitle": "أضف الخدمات التي يوفرها كراجك",
  "active_services": "خدماتك الحالية",
  "add_service": "إضافة خدمة",
  "custom_service": "خدمة مخصصة",
  "custom_service_hint": "مثال: موقف دراجات نارية",
  "add": "إضافة",
  "service_added": "تمت إضافة الخدمة",
  "service_removed": "تمت إزالة الخدمة",

  // التحقق من نموذج الحجز
  "please_select_date": "الرجاء اختيار تاريخ الحجز",
  "please_select_start_time": "الرجاء اختيار وقت البدء",
  "please_select_end_time": "الرجاء اختيار وقت الانتهاء",

  // عرض أرقام الهاتف في بطاقات الحجز
  "garage_owner_phone": "هاتف صاحب الكراج",
  "car_owner_phone": "هاتف صاحب السيارة",

  // إعادة تصميم شاشة الحجز
  "estimated_total": "الإجمالي المتوقع",
  "jod": "دينار",
  "per_hour": "/ ساعة",
  "select_date": "اختر التاريخ",
  "select_time": "اختر الوقت",
  "duration": "المدة",
  "hours": "ساعات",
  "proceed_to_payment": "المتابعة للدفع",

  // طريقة الدفع (واجهة صاحب الكراج)
  "payment_method": "طريقة الدفع",
  "paid": "مدفوع",
  "cash_pending": "نقد عند الوصول",

  // تسميات خطوات شاشة الحجز
  "time": "الوقت",
  "free": "مجاني",

  // طوابع وقت الإشعارات
  "just_now": "الآن",
  "ago": "مضت",

  // المفضلة
  "explore_garages_hint": "استكشف الكراجات واضغط ♥ لحفظها",

  // تأكيد تسجيل الخروج
  "logout_confirm_title": "تسجيل الخروج",
  "logout_confirm_message": "هل أنت متأكد من تسجيل الخروج؟",

  // تقييم الكراج
  "please_select_rating": "الرجاء اختيار عدد النجوم",

  // البحث عن كراجات
  "try_different_search": "جرب كلمة بحث أو مدينة مختلفة",
};
